name: AuctionHouse
version: ${project.version}
main: net.akarian.auctionhouse.AuctionHouse
api-version: 1.14
description: Auction House plugin.
author: Austin/KaYoz
database: true
depend:
  - Vault
softdepend:
  - Citizens
  - PlaceholderAPI
  - GemsEconomy
  - floodgate
commands:
  auctionhouse:
    description: Main Auction House command.
    aliases:
      - ah
      - ahouse
      - auction
  ahadmin:
    description: Auction House Admin command.
    permission: auctionhouse.admin
    aliases:
      - aha
      - ahouseadmin
      - auctionadmin
      - auctionhouseadmin
permissions:
  auctionhouse.help:
    description: Auction House help command.
    default: true
  auctionhouse.list:
    default: false
    description: Auction House List command.
  auctionhouse.delay.bypass:
    default: op
    description: Bypass the delay in-between listings.
  auctionhouse.search:
    description: Search the Auction House.
    default: true
  auctionhouse.expired:
    description: View your expired Listings.
    default: false
  auctionhouse.settings:
    description: View your expired Listings.
    default: false
  auctionhouse.admin:
    default: op
    description: Auction House Admin command.
  auctionhouse.admin.help:
    default: op
    description: Auction House Admin help menu.
  auctionhouse.admin.update:
    default: false
    description: Auction House Admin update command.
  auctionhouse.admin.database:
    default: false
    description: Auction House Admin database command.
  auctionhouse.admin.database.transfer:
    description: Allows the player to transfer the database type.
    default: false
  auctionhouse.admin.reload:
    default: false
    description: Auction House Admin reload command.
  auctionhouse.admin.settings:
    default: false
    description: Edit Auction House server and default player settings.
  auctionhouse.admin.npc:
    default: false
    description: Edit the Auction House NPCs.
  auctionhouse.use:
    default: true
    description: Allow the player to open the Auction House.
  auctionhouse.admin.edit:
    default: op
    description: Allow for the editing of Auction House layouts.
