name: AuctionHouse
version: 1.0.0_PRE-3
main: net.akarian.auctionhouse.AuctionHouse
api-version: 1.14
description: Auction House plugin.
author: Austin/KaYoz
database: true
depend:
  - Vault
softdepend:
  - Citizens
  - PlaceholderAPI
commands:
  auctionhouse:
    description: Main AuctionHouse command.
    aliases:
      - ah
      - ahouse
      - auction
  ahadmin:
    description: AuctionHouse Admin command.
    aliases:
      - aha
      - ahouseadmin
      - auctionadmin
      - auctionhouseadmin
permissions:
  auctionhouse.help:
    description: AuctionHouse help command.
    default: true
  auctionhouse.admin:
    default: op
    description: AuctionHouse Admin command.
  auctionhouse.list:
    default: false
    description: AuctionHouse List command.
  auctionhouse.delay.bypass:
    default: op
    description: Bypass the delay in-between listings.
  auctionhouse.search:
    description: Search the Auction House.
    default: true
  auctionhouse.expired:
    description: View your expired Listings.
    default: false

